### ISSUE TITLE
No static field tvAddress of type I in class Lcom/vanillaplacepicker

### ISSUE THREAD

**Issue by kavathiyamahesh** [Mindinventory/vanilla-place-picker#33]
`
java.lang.NoSuchFieldError: No static field tvAddress of type I in class Lcom/vanillaplacepicker/R$id; or its superclasses (declaration of 'com.vanillaplacepicker.R$id' appears in /data/app/com.instadel-ZuFwShIQZhDmvPYq3zCgRg==/base.apk)
        at com.vanillaplacepicker.presentation.map.VanillaMapActivity.initViews(VanillaMapActivity.kt:71)
        at com.vanillaplacepicker.presentation.common.VanillaBaseActivity.onCreate(VanillaBaseActivity.kt:22)
        at com.vanillaplacepicker.presentation.common.VanillaBaseViewModelActivity.onCreate(VanillaBaseViewModelActivity.kt:13)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

**Comment by kavathiyamahesh** [comment]
please rename toolbar.xml to avoid such kind of issue.
